API_BASE = "http://environment.data.gov.uk/hydrology/id/stations"
VERIFY = False
LOCATION_TO_HARDNESS = {
   "Bath": "Hard",
   "Birmingham": "Moderate/Hard",
   "Blackburn": "Soft",
   "Blackpool": "Soft",
   "Bolton": "Soft",
   "Bournemouth": "Hard",
   "Bradford": "Soft",
   "Brighton": "Hard",
   "Bristol": "Hard",
   "Bromley": "Hard",
   "Cambridge": "Hard",
   "Canterbury": "Hard",
   "Carlisle": "Hard/Soft",
   "Chelmsford": "Hard",
   "Chester": "Soft/Hard",
   "Cleveland [Teesside]": "Soft",
   "Colchester": "Hard",
   "Coventry": "Hard",
   "Crewe": "Soft",
   "Croydon": "Hard",
   "Darlington": "Soft",
   "Dartford": "Hard",
   "Derby": "Hard/Soft",
   "Doncaster": "Hard",
   "Dorchester": "Hard",
   "Dudley": "Moderate",
   "Durham": "Soft",
   "Enfield": "Hard",
   "Exeter": "Soft",
   "Gloucester": "Moderate",
   "Guildford": "Hard",
   "Halifax": "Soft",
   "Harrogate": "Soft",
   "Harrow": "Hard",
   "Hemel Hempstead": "Hard",
   "Hereford": "Moderate",
   "Huddersfield": "Soft",
   "Hull": "Hard",
   "Ilford": "Hard",
   "Ipswich": "Hard",
   "Kingston upon Thames": "Hard",
   "Lancaster": "Soft",
   "Leeds": "Hard/Soft",
   "Leicester": "Hard",
   "Lincoln": "Hard",
   "Liverpool": "Soft",
   "London E": "Hard",
   "London EC": "Hard",
   "London N": "Hard",
   "London NW": "Hard",
   "London SE": "Hard",
   "London SW": "Hard",
   "London W": "Hard",
   "London WC": "Hard",
   "Luton": "Hard",
   "Manchester": "Soft",
   "Medway / Rochester": "Hard",
   "Milton Keynes": "Hard",
   "Newcastle upon Tyne": "Hard",
   "Northampton": "Hard",
   "Norwich": "Hard",
   "Nottingham": "Hard",
   "Oldham": "Soft",
   "Oxford": "Hard",
   "Peterborough": "Hard",
   "Plymouth": "Soft",
   "Portsmouth": "Hard",
   "Preston": "Soft",
   "Reading": "Hard",
   "Redhill": "Moderate",
   "Romford": "Hard",
   "Salisbury": "Hard",
   "Sheffield": "Hard",
   "Slough": "Hard",
   "Southall Uxbridge": "Hard",
   "Southampton": "Hard",
   "Southend-on-Sea": "Hard",
   "St Albans": "Hard",
   "Stevenage": "Hard",
   "Stockport": "Soft",
   "Stoke-on-Trent": "Hard",
   "Sunderland": "Hard",
   "Sutton": "Hard",
   "Swindon": "Hard",
   "Taunton": "Moderate",
   "Telford": "Hard",
   "Tonbridge": "Hard",
   "Torquay": "Soft",
   "Truro": "Soft",
   "Twickenham": "Hard",
   "Wakefield": "Hard",
   "Walsall": "Moderate",
   "Warrington": "Soft",
   "Watford": "Hard",
   "Wigan": "Soft",
   "Wolverhampton": "Hard",
   "Worcester": "Moderate",
   "York": "Hard",
   
   # Wales
   "Cardiff": "Soft",
   "Llandrindod Wells": "Moderate",
   "Llandudno": "Soft/Moderate",
   "Newport": "Moderate",
   "Swansea": "Soft",
   "Shrewsbury": "Moderate",
   
   # Scotland
   "Aberdeen": "Soft",
   "Dundee": "Soft",
   "Dumfries & Galloway": "Soft",
   "Edinburgh": "Soft/Moderate",
   "Falkirk & Stirling": "Soft",
   "Glasgow": "Soft",
   "Galashiels": "Soft",
   "Inverness": "Soft",
   "Kilmarnock": "Soft",
   "Kirkwall": "Soft",
   "Kirkcaldy": "Soft",
   "Motherwell": "Soft",
   "Paisley": "Soft",
   "Perth": "Soft"
}
